'use strict'
let SkillList = [
  {name: "Android", type: "platform", image: "android.svg", link: "https://www.android.com"},
  {name: "iOS", type: "platform", image: "ios.svg", link: "https://www.apple.com/jp/ios"},
  {name: "Linux", type: "platform", image: "tux.svg", link: "https://www.linux.com"},
  {name: "macOS", type: "platform", image: "macos.svg", link: "https://www.apple.com/jp/macos/"},
  {name: "Windows", type: "platform", image: "windows.svg", link: "https://www.microsoft.com/ja-jp/windows"},
  {name: "Assembly Language", type: "programming", image: "default.svg", link: ""},
  {name: "C", type: "programming", image: "c.svg", link: ""},
  {name: "Clojure", type: "programming", image: "clojure.svg", link: "https://clojure.org", child: ["ClojureScript", "JavaScript"]},
  {name: "COBOL", type: "programming", image: "default.svg", link: ""},
  {name: "CoffeeScript", type: "programming", image: "coffeescript.svg", link: "https://coffeescript.org"},
  {name: "Crystal", type: "programming", image: "crystal.svg", link: "https://crystal-lang.org"},
  {name: "C#", type: "programming", image: "c-sharp.svg", link: "", child: [".NET", "Engine", "Unity"]},
  {name: "C++", type: "programming", image: "c-plusplus.svg", link: "", child: ["Library", "Boost", "Framework", "Qt", "Engine", "Unreal Engine"]},
  {name: "D", type: "programming", image: "dlogo_2015.svg", link: "https://dlang.org"},
  {name: "Dart", type: "programming", image: "dart.svg", link: "https://dart.dev", child: ["UI toolkit", "Flutter"]},
  {name: "Delphi/Object Pascal", type: "programming", image: "default.svg", link: "http://www.embarcadero.com/jp/products/delphi"},
  {name: "Elixir", type: "programming", image: "elixir.svg", link: "https://elixir-lang.org", child: ["Framework", "Phoenix"]},
  {name: "Elm", type: "programming", image: "elm.svg", link: "https://elm-lang.org"},
  {name: "Erlang", type: "programming", image: "erlang.svg", link: "https://www.erlang.org"},
  {name: "FORTRAN", type: "programming", image: "fortran.svg", link: "https://fortran-lang.org"},
  {name: "F#", type: "programming", image: "fsharp.svg", link: "https://fsharp.org", child: [".NET"]}, 
  {name: "Go", type: "programming", image: "go.svg", link: "https://golang.org", child: ["Framework", "Hugo"]},
  {name: "Groovy", type: "programming", image: "groovy.png", link: "https://groovy-lang.org"},
  {name: "Haskell", type: "programming", image: "haskell.svg", link: "https://www.haskell.org"},
  {name: "Haxe", type: "programming", image: "haxe.svg", link: "https://haxe.org", child: ["Compile", "C++", "JavaScript", "Lua", "C#", "PHP", "Python"]},
  {name: "Java", type: "programming", image: "java.svg", link: "https://www.oracle.com/java", child: ["Framework", "Jakarta EE", "Play", "Spring", "Struts"]},
  {name: "JavaScript", type: "programming", image: "javascript.svg", link: "", child: ["AltJS", "CoffeeScript", "Elm", "LiveScript", "PureScript", "TypeScript", "Library", "jQuery", "Environment", "Node.js", "Runtime", "Deno", "Bun", "Framework", "Angular", "React", "Svelte", "Vue.js"]},
  {name: "Julia", type: "programming", image: "julia.svg", link: "https://julialang.org"},
  {name: "Kotlin", type: "programming", image: "kotlin.svg", link: "https://kotlinlang.org"},
  {name: "Lisp", type: "programming", image: "default.svg", link: "", child: ["Clojure", "Scheme"]},
  {name: "LiveScript", type: "programming", image: "livescript.svg", link: "http://livescript.net"},
  {name: "Lua", type: "programming", image: "lua.gif", link: "https://www.lua.org"},
  {name: "Nim", type: "programming", image: "nim.png", link: "https://nim-lang.org", child: ["Compile", "C", "C++", "JavaScript", "Objective-C"]},
  {name: "OCaml", type: "programming", image: "ocaml.svg", link: "https://ocaml.org"},
  {name: "Objective-C", type: "programming", image: "default.svg", link: "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html"},
  {name: "Perl", type: "programming", image: "perl.svg", link: "https://www.perl.org"},
  {name: "Prolog", type: "programming", image: "default.svg", link: ""},
  {name: "PHP", type: "programming", image: "php.svg", link: "https://www.php.net", child: ["Hack", "CMS", "WordPress", "Web framework", "CakePHP", "CodeIgniter", "FuelPHP", "Laravel", "Phalcon", "Symfony"]},
  {name: "PureScript", type: "programming", image: "purescript.svg", link: "https://www.purescript.org"},
  {name: "Python", type: "programming", image: "python.svg", link: "https://www.python.org", child: ["Web framework", "Bottle", "Django", "Flask", "Pyramid", "Tornado", "Machine Learning", "PyTorch", "scikit-learn", "Tensorflow"]},
  {name: "R", type: "programming", image: "r-lang.svg", link: "https://www.r-project.org"},
  {name: "Ruby", type: "programming", image: "ruby.svg", link: "https://www.ruby-lang.org", child: ["Web framework", "Rails"]},
  {name: "Rust", type: "programming", image: "rust.svg", link: "http://www.rust-lang.org"},
  {name: "Scala", type: "programming", image: "scala.svg", link: "https://www.scala-lang.org", child: ["on the JVM", "Java", "Scala.js", "JavaScript"]},
  {name: "Scratch", type: "programming", image: "scratch.png", link: "https://scratch.mit.edu"},
  {name: "Swift", type: "programming", image: "swift.svg", link: "https://swift.org"},
  {name: "Tcl", type: "programming", image: "tcl.png", link: "https://www.tcl-lang.org", child: ["GUI toolkit", "Tk"]},
  {name: "TypeScript", type: "programming", image: "typescript.svg", link: "https://www.typescriptlang.org"},
  {name: "V", type: "programming", image: "vlang.svg", link: "https://vlang.io"},
  {name: "Visual Basic", type: "programming", image: "vb.svg", link: "", child: [".NET"]},
  {name: "HTML", type: "markup-markdown", image: "html-5.svg", link: "", child: ["Template engine", "Haml", "Pug", "Scalate", "Slim"]},
  {name: "Markdown", type: "markup-markdown", image: "markdown.svg", link: "https://daringfireball.net/projects/markdown/"},
  {name: "MathML", type: "markup-markdown", image: "default.svg", link: "https://www.w3.org/Math/"},
  {name: "SAML", type: "markup-markdown", image: "default.svg", link: "https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0.html"},
  {name: "TeX", type: "markup-markdown", image: "default.svg", link: "https://tug.org"},
  {name: "XAML", type: "markup-markdown", image: "default.svg", link: "", child: ["Framework", "Avalonia"]},
  {name: "XML", type: "markup-markdown", image: "default.svg", link: ""},
  {name: "CSS", type: "stylesheet", image: "css-3.svg", link: "https://www.w3.org/Style/CSS/", child: ["Extension", "Less", "Sass", "Stylus", "Framework", "Bootstrap", "CSSinJS", "Emotion", "styled-components"]},
  {name: "Sass", type: "stylesheet", image: "sass.svg", link: "https://sass-lang.com"},
  {name: "Graph-QL", type: "query", image: "graphql.svg", link: "https://graphql.org", child: ["Platform", "Apollo", "Client", "Relay"]},
  {name: "SQL", type: "query", image: "default.svg", link: "", child: ["Relational", "MariaDB", "Microsoft SQL Server", "MySQL", "PostgreSQL", "SQLite"]},
  {name: "SystemVerilog", type: "hardware-description", image: "default.svg", link: ""},
  {name: "Verilog", type: "hardware-description", image: "default.svg", link: ""},
  {name: "VHDL", type: "hardware-description", image: "default.svg", link: ""},
  {name: ".NET", type: "framework", image: ".net.svg", link: "https://dot.net/"},
  {name: "jQuery", type: "framework", image: "jquery.svg", link: "https://jquery.com"},
  {name: "Node.js", type: "framework", image: "nodejs.svg", link: "https://nodejs.org", child: ["Framework", "Express", "fastify", "Koa"]},
  {name: "React", type: "framework", image: "react.svg", link: "https://reactjs.org", child: ["Framework", "Gatsby", "Next.js"]},
  {name: "Vue.js", type: "framework", image: "vuejs.svg", link: "https://vuejs.org", child: ["Framework", "Nuxt.js"]},
  {name: "Nuxt.js", type: "framework", image: "nuxtjs.svg", link: "https://nuxtjs.org"},
  {name: "Angular", type: "framework", image: "angular.svg", link: "https://angular.io"},
  {name: "Rails", type: "framework", image: "rails.svg", link: "https://rubyonrails.org"},
  {name: "J", type: "programming", image: "default.svg", link: "https://www.jsoftware.com"},
  {name: "Arduino", type: "programming", image: "rails.svg", link: "https://www.arduino.cc"},
  {name: "Scheme", type: "programming", image: "default.svg", link: "http://www.scheme-reports.org", child: ["Racket"]},
  {name: "Racket", type: "programming", image: "default.svg", link: "https://racket-lang.org"},
  {name: "Command Prompt", type: "commandline", image: "default.svg", link: ""},
  {name: "PowerShell", type: "commandline", image: "powershell.svg", link: "https://microsoft.com/powershell"},
  {name: "bash", type: "commandline", image: "bash.svg", link: "https://www.gnu.org/software/bash/"},
  {name: "dash", type: "commandline", image: "default.svg", link: "http://gondor.apana.org.au/~herbert/dash/"},
  {name: "fish", type: "commandline", image: "fish.svg", link: "https://fishshell.com"},
  {name: "ksh", type: "framework", image: "default.svg", link: "http://www.kornshell.org"},
  {name: "tcsh", type: "commandline", image: "default.svg", link: "https://www.tcsh.org"},
  {name: "zsh", type: "commandline", image: "default.svg", link: "https://www.zsh.org"},
  {name: "Qt", type: "framework", image: "qt.svg", link: "https://www.qt.io"},
  {name: "Tk", type: "framework", image: "default.svg", link: ""},
  {name: "Avalonia", type: "framework", image: "avalonia.png", link: "https://avaloniaui.net"},
  {name: "Raspberry Pi", type: "platform", image: "raspberrypi.svg", link: "https://www.raspberrypi.org"},
  {name: "Flutter", type: "framework", image: "fluter.svg", link: "https://flutter.dev"},
  {name: "Express", type: "framework", image: "default.svg", link: "https://expressjs.com", child: ["NestJS"]},
  {name: "fastify", type: "framework", image: "fastify.svg", link: "https://www.fastify.io", child: ["NestJS"]},
  {name: "Next.js", type: "framework", image: "nextjs.svg", link: "https://nextjs.org"},
  {name: "NestJS", type: "framework", image: "nestjs.svg", link: "https://nestjs.com"},
  {name: "CakePHP", type: "framework", image: "cakephp.svg", link: "https://cakephp.org"},
  {name: "CodeIgniter", type: "framework", image: "codeigniter.svg", link: "https://www.codeigniter.com"},
  {name: "FuelPHP", type: "framework", image: "fuelphp.svg", link: "https://fuelphp.com"},
  {name: "Laravel", type: "framework", image: "laravel.svg", link: "https://laravel.com"},
  {name: "Symfony", type: "framework", image: "symfony.svg", link: "https://symfony.com"},
  {name: "Bottle", type: "framework", image: "default.svg", link: "https://bottlepy.org"},
  {name: "Django", type: "framework", image: "django.svg", link: "https://www.djangoproject.com"},
  {name: "Flask", type: "framework", image: "flask.svg", link: "https://palletsprojects.com/p/flask/"},
  {name: "Tornado", type: "framework", image: "tornado.png", link: "https://www.tornadoweb.org"},
  {name: "Koa", type: "framework", image: "koa.png", link: "https://koajs.com"},
  {name: "Phalcon", type: "framework", image: "phalcon.svg", link: "https://phalcon.io"},
  {name: "WordPress", type: "CMS", image: "wordpress.svg", link: "https://wordpress.com"},
  {name: "Pyramid", type: "framework", image: "default.svg", link: "https://trypyramid.com"},
  {name: "Bootstrap", type: "framework", image: "bootstrap.svg", link: "https://getbootstrap.com"},
  {name: "Less", type: "stylesheet", image: "less.png", link: "https://lesscss.org"},
  {name: "styled-components", type: "stylesheet", image: "styled-components.svg", link: "https://styled-components.com"},
  {name: "Stylus", type: "stylesheet", image: "stylus.svg", link: "https://stylus-lang.com"},
  {name: "Boost", type: "library", image: "boost.png", link: "https://www.boost.org"},
  {name: "Hack", type: "programming", image: "huck.svg", link: "https://hacklang.org"},
  {name: "Deno", type: "runtime", image: "deno.svg", link: "https://deno.land", child: ["Web framework", "Fresh"]},
  {name: "Unity", type: "engine", image: "unity.svg", link: "https://unity.com"},
  {name: "Emotion", type: "stylesheet", image: "emotion.png", link: "https://emotion.sh"},
  {name: "Gatsby", type: "framework", image: "gatsby.svg", link: "https://www.gatsbyjs.com"},
  {name: "Svelte", type: "framework", image: "svelte.svg", link: "https://svelte.dev"},
  {name: "Hugo", type: "framework", image: "hugo.svg", link: "https://gohugo.io"},
  {name: "Git", type: "version-control", image: "git.svg", link: "https://git-scm.com", child: ["Development platform", "GitHub"]},
  {name: "GitHub", type: "service", image: "github.svg", link: "https://github.com"},
  {name: "Subversion", type: "version-control", image: "subversion.svg", link: "https://subversion.apache.org"},
  {name: "Mercurial", type: "version-control", image: "mercurial.png", link: "https://www.mercurial-scm.org"},
  {name: "Docker", type: "container-virtualization", image: "docker.png", link: "https://www.docker.com"},
  {name: "Kubernetes", type: "container-virtualization", image: "kubernetes.svg", link: "https://kubernetes.io"},
  {name: "LXC", type: "container-virtualization", image: "lxc.svg", link: "https://linuxcontainers.org"},
  {name: "AWS", type: "infrastructure", image: "aws.svg", link: "https://aws.amazon.com"},
  {name: "Azure", type: "infrastructure", image: "azure.svg", link: "https://azure.microsoft.com"},
  {name: "GCP", type: "infrastructure", image: "gcp.svg", link: "https://cloud.google.com"},
  {name: "Heroku", type: "infrastructure", image: "default.svg", link: "https://heroku.com"},
  {name: "Phoenix", type: "framework", image: "phoenix.svg", link: "https://www.phoenixframework.org"},
  {name: "SystemC", type: "hardware-description", image: "default.svg", link: "https://systemc.org"},
  {name: "Jakarta EE", type: "framework", image: "default.svg", link: "https://jakarta.ee"},
  {name: "Play", type: "framework", image: "play.svg", link: "https://www.playframework.com"},
  {name: "Spring", type: "framework", image: "spring.svg", link: "https://spring.io"},
  {name: "Struts", type: "framework", image: "struts.svg", link: "https://struts.apache.org"},
  {name: "ReactiveX", type: "programming", image: "reactivex.png", link: "http://reactivex.io"},
  {name: "ABAP", type: "programming", image: "default.svg", link: ""},
  {name: "OCI", type: "infrastructure", image: "oci.svg", link: "https://www.oracle.com/jp/cloud"},
  {name: "PyTorch", type: "machinelearning", image: "pytorch.svg", link: "https://pytorch.org"},
  {name: "Tensorflow", type: "machinelearning", image: "tensorflow.svg", link: "https://www.tensorflow.org"},
  {name: "IBMCloud", type: "programming", image: "default.svg", link: "https://www.ibm.com/jp-ja/cloud"},
  {name: "nadesiko", type: "programming", image: "default.svg", link: "https://nadesi.com"},
  {name: "dolittle", type: "programming", image: "default.svg", link: "https://dolittle.eplang.jp"},
  {name: "produire", type: "programming", image: "default.svg", link: "https://rdr.utopiat.net"},
  {name: "PostCSS", type: "stylesheet", image: "postcss.svg", link: "https://postcss.org"},
  {name: "tailwindcss", type: "stylesheet", image: "tailwindcss.svg", link: "https://tailwindcss.com"},
  {name: "WebAssembly", type: "programming", image: "webassembly.svg", link: "https://webassembly.org"},
  {name: "AHDL", type: "hardware-description", image: "default.svg", link: ""},
  {name: "Apache HTTP Server", type: "web-server", image: "httpd.svg", link: "https://httpd.apache.org"},
  {name: "NGINX", type: "web-server", image: "nginx.svg", link: "https://www.nginx.co.jp"},
  {name: "Microsoft IIS", type: "web-server", image: "default.svg", link: "https://www.iis.net"},
  {name: "Unreal Engine", type: "engine", image: "unrealengine.svg", link: "https://www.unrealengine.com"},
  {name: "Q#", type: "programming", image: "default.svg", link: "https://docs.microsoft.com/en-us/azure/quantum/"},
  {name: "Relay", type: "query", image: "relay.svg", link: "https://relay.dev"},
  {name: "Apollo", type: "query", image: "default.svg", link: "https://www.apollographql.com"},
  {name: "MySQL", type: "database", image: "default.svg", link: "https://www.mysql.com"},
  {name: "PostgreSQL", type: "database", image: "postgresql.svg", link: "https://www.postgresql.org"},
  {name: "Microsoft SQL Server", type: "database", image: "default.svg", link: "https://www.microsoft.com/ja-jp/sql-server/"},
  {name: "NoSQL", type: "query", image: "default.svg", link: "", child: ["Document", "MongoDB", "Key-Value", "Redis", "Graph", "Neo4j", "Search", "Elasticsearch", "Wide Column", "Cassandra"]},
  {name: "MariaDB", type: "database", image: "mariadb.svg", link: "https://mariadb.org"},
  {name: "SQLite", type: "database", image: "sqlite.svg", link: "https://www.sqlite.org"},
  {name: "Redis", type: "database", image: "redis.svg", link: "https://redis.io"},
  {name: "MongoDB", type: "database", image: "default.svg", link: "https://www.mongodb.com"},
  {name: "Neo4j", type: "database", image: "neo4j.svg", link: "https://neo4j.com"},
  {name: "Elasticsearch", type: "database", image: "elasticsearch.svg", link: "https://www.elastic.co/jp/elasticsearch/"},
  {name: "Cassandra", type: "database", image: "cassandra.svg", link: "https://cassandra.apache.org"},
  {name: "OpenShift", type: "container-virtualization", image: "openshift.svg", link: "https://openshift.com"},
  {name: "Zig", type: "programming", image: "zig.svg", link: "https://ziglang.org"},
  {name: "CUE", type: "data", image: "default.svg", link: "https://cuelang.org"},
  {name: "JSON", type: "data", image: "default.svg", link: "https://www.json.org"},
  {name: "YAML", type: "data", image: "default.svg", link: "https://yaml.org"},
  {name: "scikit-learn", type: "machinelearning", image: "scikit-learn.svg", link: "https://scikit-learn.org"},
  {name: "Haml", type: "template-engine", image: "haml.png", link: "https://haml.info"},
  {name: "Cordova", type: "multi-platform", image: "cordova.png", link: "https://cordova.apache.org"},
  {name: "Electron", type: "multi-platform", image: "electron.svg", link: "https://www.electronjs.org"},
  {name: "React Native", type: "multi-platform", image: "react.svg", link: "https://reactnative.dev"},
  {name: "Tauri", type: "multi-platform", image: "tauri.png", link: "https://tauri.app" },
  {name: "Fresh", type: "framework", image: "fresh.svg", link: "https://fresh.deno.dev" },
  {name: "Chisel", type: "hardware-description", image: "chisel.png", link: "https://www.chisel-lang.org" },
  {name: "Pug", type: "template-engine", image: "pug.svg", link: "http://slim-lang.com" },
  {name: "Scalate", type: "template-engine", image: "scalate.png", link: "https://scalate.github.io/scalate/" },
  {name: "Slim", type: "template-engine", image: "slim.png", link: "https://pugjs.org" },
  {name: "Ionic", type: "multi-platform", image: "ionic.svg", link: "https://ionic.io" },
  {name: "M5Stack", type: "platform", image: "m5stack.svg", link: "https://www.m5stack.com" },
  {name: "Bun", type: "programming", image: "bun.png", link: "https://bun.sh" },
  {name: "Podman", type: "container-virtualization", image: "podman.svg", link: "https://podman.io" },
  {name: "Azure RTOS ThreadX", type: "rtos", image: "default.svg", link: "https://azure.microsoft.com/en-us/services/rtos/" },
  {name: "FreeRTOS", type: "rtos", image: "freertos.png", link: "https://www.freertos.org" },
  {name: "Zephyr", type: "rtos", image: "zephyr.svg", link: "https://www.zephyrproject.org" },
  {name: "CircleCI", type: "cicd", image: "circleci.svg", link: "https://circleci.com" },
  {name: "Dagger", type: "cicd", image: "dagger.svg", link: "https://dagger.io" },
  {name: "Jenkins", type: "cicd", image: "jenkins.svg", link: "https://www.jenkins.io" },
  {name: "GitHub Actions", type: "cicd", image: "github-actions.svg", link: "https://github.com/features/actions" },
  {name: "Tekton", type: "cicd", image: "tekton.svg", link: "https://tekton.dev" },
  {name: "Travis CI", type: "cicd", image: "travis.svg", link: "https://www.travis-ci.com" }
];
